version: "3"

services:
  redis:
    image: redis:alpine
  db:
    build: ./psql/.
  worker:
    build: ./worker/.
    environment:
      PSQL_HOST: "db"
      PSQL_PWD: "123test"
  vote:
    build: ./PyVote/.
    ports:
      - 5000:83
    environment:
      REDIS_HOST: "redis"
      PSQL_HOST: "db"
      PSQL_PWD: "123test"
  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
