version: "3"

services:
  redis:
    image: redis:alpine
  db:
    build: ./psql/.
  vote:
    build: ./PyVote/.
    ports:
      - 5000:83
    environment:
      REDIS_HOST: "redis"
      PSQL_HOST: "db"
